# Generated by Django 4.0 on 2021-12-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='title',
        ),
        migrations.AlterField(
            model_name='job',
            name='body',
            field=models.TextField(max_length=255),
        ),
    ]
